### Count of given inputs

In [6]:
import pandas as pd
words=[]
n=int(input("Enter a number to create strings: "))
for i in range(0,n):
    string=input("Enter a string: ")
    words.append(string)
print(pd.value_counts(words))
    

Enter a number to create strings: 6
Enter a string: abcd
Enter a string: ijkl
Enter a string: abcd
Enter a string: pqrs
Enter a string: abcd
Enter a string: ijkl
abcd    3
ijkl    2
pqrs    1
dtype: int64


### Validation of E-mail

In [5]:
import re
def emailID(email):
    pattern = '^[0-9a-z][0-9a-z_.]{5,30}[@][a-z0-9]{3,18}[.][a-z]{2,4}$'
    if re.match(pattern,email):
        print("Valid")
    else:
        print("Invalid")
n=int(input("Enter number of mails to create: "))
for i in range(0,n):
    email=input("Enter mail id : ")
    emailID(email)

Enter number of mails to create: 1
Enter mail id : raja.narayana08@gmail.com
Valid


In [13]:
import pandas as pd
words=[]
n=int(input("Enter a number to create strings: "))
for i in range(0,n):
    string=input("Enter a string: ")
    words.append(string)
print(words.count(words))
    

Enter a number to create strings: 2
Enter a string: acd
0
Enter a string: acd
0


### Subset of an array

In [1]:
def subset(arr, N, K): 
    f = [0 for i in range(K)] 
    
    for i in range(N): 
        f[arr[i] % K] += 1
        
    if (K % 2 == 0): 
        f[K/2] = min(f[K / 2], 1) 
  
    res = min(f[0], 1) 
  
    for i in range(1,(K // 2) + 1): 
        res += max(f[i], f[K - i]) 
  
    return res 
      
arr = [1,7,2,4] 
N = len(arr) 
K = 3
print(subset(arr, N, K)) 

3


### Addition of two matrices

In [17]:
import numpy as np
matrix1=np.array([[12,13,14],[75,25,78],[12,65,48]])
matrix2=np.array([[78,98,10],[45,65,75],[45,76,38]])
print(np.add(matrix1,matrix2))

[[ 90 111  24]
 [120  90 153]
 [ 57 141  86]]


### Removing punctuations from a string

In [4]:
string=input("Enter a string")
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for x in string.lower(): 
    if x in punctuations: 
        string = string.replace(x, "") 
print(string)

Enter a string*raja%narayana(murhty)
rajanarayanamurhty


### transpose of a matrix

In [11]:
import numpy as np
matrix1=np.array([[12,13,14],[75,25,78],[12,65,48]])
print(matrix1.T)

[[12 75 12]
 [13 25 65]
 [14 78 48]]


### Disarium Number in python
* Disarium number --- A number is said to be the Disarium number when the sum of its digit raised to the power of their respective positions becomes equal to the number itself.
* Example : 1^1+ 7^2 + 5^3 = 1+ 49 + 125 = 175

In [6]:
def Length(n):    
    length = 0    
    while(n != 0):    
        length = length + 1
        n = n//10    
    return length    
     
num = int(input("Enter a number : "))  
rem = 0
sum = 0
len = Length(num)
n = num   
       
while(num > 0):    
    rem = num%10
    sum = sum + (rem**len)
    num = num//10
    len = len - 1      
if(sum == n):    
    print(str(n) + " is a disarium number")
else:    
    print(str(n) + " is not a disarium number")

Enter a number : 175
175 is a disarium number
